# TCL File Generated by Component Editor 19.2
# Thu Aug 01 10:14:31 PDT 2019
# DO NOT MODIFY


# 
# TimeServo "TimeServo" v1.0
#  2019.08.01.10:14:31
# 
# 

# 
# request TCL package from ACDS 19.4
# 
package require  qsys 19.4


# 
# module TimeServo
# 
set_module_property DESCRIPTION ""
set_module_property NAME TimeServo
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "Atomic Rules LLC"
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME TimeServo
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false
set_module_property LOAD_ELABORATION_LIMIT 0
set_module_property ELABORATION_CALLBACK elaborate_callback

set bsv_file_deps {../common/bsv/SyncFIFO.v
	../common/bsv/SyncFIFOLevel.v
	../common/bsv/SyncRegister.v
	../common/bsv/SyncFIFO1.v
	../common/bsv/FIFO2.v
	../common/bsv/FIFOL1.v
	../common/bsv/SyncHandshake.v
	../common/bsv/SyncResetA.v
}
# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL timeServo
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file timeServo.v VERILOG PATH timeServo.v TOP_LEVEL_FILE
foreach f $bsv_file_deps {
	add_fileset_file [file tail $f] VERILOG PATH $f
}

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL timeServo
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file timeServo.v VERILOG PATH timeServo.v
foreach f $bsv_file_deps {
	add_fileset_file [file tail $f] VERILOG PATH $f
}
# 
# parameters
# 
add_parameter numCDC INTEGER 1 "Number of now interfaces"



# 
# display items
# 


# 
# connection point ref_clk
# 
add_interface ref_clk clock end
set_interface_property ref_clk ENABLED true
set_interface_property ref_clk EXPORT_OF ""
set_interface_property ref_clk PORT_NAME_MAP ""
set_interface_property ref_clk CMSIS_SVD_VARIABLES ""
set_interface_property ref_clk SVD_ADDRESS_GROUP ""
set_interface_property ref_clk IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port ref_clk ref_clk clk Input 1


# 
# connection point ref_rstn
# 
add_interface ref_rstn reset end
set_interface_property ref_rstn associatedClock s_axi_aclk
set_interface_property ref_rstn synchronousEdges BOTH
set_interface_property ref_rstn ENABLED true
set_interface_property ref_rstn EXPORT_OF ""
set_interface_property ref_rstn PORT_NAME_MAP ""
set_interface_property ref_rstn CMSIS_SVD_VARIABLES ""
set_interface_property ref_rstn SVD_ADDRESS_GROUP ""
set_interface_property ref_rstn IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port ref_rstn ref_rstn reset_n Input 1


# 
# connection point s_axi_aclk
# 
add_interface s_axi_aclk clock end
set_interface_property s_axi_aclk ENABLED true
set_interface_property s_axi_aclk EXPORT_OF ""
set_interface_property s_axi_aclk PORT_NAME_MAP ""
set_interface_property s_axi_aclk CMSIS_SVD_VARIABLES ""
set_interface_property s_axi_aclk SVD_ADDRESS_GROUP ""
set_interface_property s_axi_aclk IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port s_axi_aclk s_axi_aclk clk Input 1


# 
# connection point now_N conduit
#
for {set i 0} {$i < 32} {incr i} {

	add_interface now_[set i] conduit end
	set_interface_property now_[set i] associatedClock ""
	set_interface_property now_[set i] associatedReset ""
	set_interface_property now_[set i] ENABLED true
	set_interface_property now_[set i] EXPORT_OF ""
	set_interface_property now_[set i] PORT_NAME_MAP ""
	set_interface_property now_[set i] CMSIS_SVD_VARIABLES ""
	set_interface_property now_[set i] SVD_ADDRESS_GROUP ""
	set_interface_property now_[set i] IPXACT_REGISTER_MAP_VARIABLES ""

	add_interface_port "now_[set i]" "now_[set i]" "now_[set i]" Output 80
	add_interface_port "now_[set i]" "now_pps_[set i]" "now_pps_[set i]" Output 1
	add_interface_port "now_[set i]" "now_clk_[set i]" "now_clk_[set i]" Input 1
}

foreach wire {{pps_src Input 1 end}
	{pfd_monitor Output 2 start}
	{now_ref Output 80 start}
	{now_pps_ref Output 1 start}} {
	set nm [lindex $wire 0]
	set io [lindex $wire 1]
	set sz [lindex $wire 2]
	set dir [lindex $wire 3]
	add_interface $nm conduit $dir
	set_interface_property $nm associatedClock ""
	set_interface_property $nm associatedReset ""
	set_interface_property $nm ENABLED true
	set_interface_property $nm EXPORT_OF ""
	set_interface_property $nm PORT_NAME_MAP ""
	set_interface_property $nm CMSIS_SVD_VARIABLES ""
	set_interface_property $nm SVD_ADDRESS_GROUP ""
	set_interface_property $nm IPXACT_REGISTER_MAP_VARIABLES ""

	add_interface_port $nm $nm $nm $io $sz
}

# 
# connection point s_axi_aresetn
# 
add_interface s_axi_aresetn reset end
set_interface_property s_axi_aresetn associatedClock s_axi_aclk
set_interface_property s_axi_aresetn synchronousEdges BOTH
set_interface_property s_axi_aresetn ENABLED true
set_interface_property s_axi_aresetn EXPORT_OF ""
set_interface_property s_axi_aresetn PORT_NAME_MAP ""
set_interface_property s_axi_aresetn CMSIS_SVD_VARIABLES ""
set_interface_property s_axi_aresetn SVD_ADDRESS_GROUP ""
set_interface_property s_axi_aresetn IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port s_axi_aresetn s_axi_aresetn reset_n Input 1


# 
# connection point altera_axi4lite_slave
# 
add_interface altera_axi4lite_slave axi4lite end
set_interface_property altera_axi4lite_slave associatedClock s_axi_aclk
set_interface_property altera_axi4lite_slave associatedReset s_axi_aresetn
set_interface_property altera_axi4lite_slave readAcceptanceCapability 1
set_interface_property altera_axi4lite_slave writeAcceptanceCapability 1
set_interface_property altera_axi4lite_slave combinedAcceptanceCapability 1
set_interface_property altera_axi4lite_slave bridgesToMaster ""
set_interface_property altera_axi4lite_slave ENABLED true
set_interface_property altera_axi4lite_slave EXPORT_OF ""
set_interface_property altera_axi4lite_slave PORT_NAME_MAP ""
set_interface_property altera_axi4lite_slave CMSIS_SVD_VARIABLES ""
set_interface_property altera_axi4lite_slave SVD_ADDRESS_GROUP ""
set_interface_property altera_axi4lite_slave IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port altera_axi4lite_slave s_axi_awvalid awvalid Input 1
add_interface_port altera_axi4lite_slave s_axi_awready awready Output 1
add_interface_port altera_axi4lite_slave s_axi_awaddr awaddr Input 12
add_interface_port altera_axi4lite_slave s_axi_awprot awprot Input 3
add_interface_port altera_axi4lite_slave s_axi_wvalid wvalid Input 1
add_interface_port altera_axi4lite_slave s_axi_wready wready Output 1
add_interface_port altera_axi4lite_slave s_axi_wdata wdata Input 32
add_interface_port altera_axi4lite_slave s_axi_wstrb wstrb Input 4
add_interface_port altera_axi4lite_slave s_axi_bvalid bvalid Output 1
add_interface_port altera_axi4lite_slave s_axi_bready bready Input 1
add_interface_port altera_axi4lite_slave s_axi_bresp bresp Output 2
add_interface_port altera_axi4lite_slave s_axi_arvalid arvalid Input 1
add_interface_port altera_axi4lite_slave s_axi_arready arready Output 1
add_interface_port altera_axi4lite_slave s_axi_araddr araddr Input 12
add_interface_port altera_axi4lite_slave s_axi_arprot arprot Input 3
add_interface_port altera_axi4lite_slave s_axi_rvalid rvalid Output 1
add_interface_port altera_axi4lite_slave s_axi_rready rready Input 1
add_interface_port altera_axi4lite_slave s_axi_rdata rdata Output 32
add_interface_port altera_axi4lite_slave s_axi_rresp rresp Output 2

proc elaborate_callback {} {
	set num_cdc [get_parameter numCDC]
	for {set i 0} {$i < 32} {incr i} {

		if { $i < $num_cdc } {
			set_interface_property now_[set i] ENABLED true			
		} else {
			set_interface_property now_[set i] ENABLED false
		}
	}

}
